##### Terminal #####

set -g default-terminal "tmux-256color"

# tmux >= 3.2
set -as terminal-features ",*:RGB"

##### General #####

set -g mouse on
set -g history-limit 100000
set -sg escape-time 100

##### Window numbering #####

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

##### Copy mode #####

setw -g mode-keys vi

##### Reload #####

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded tmux config"

##### Current directory #####

bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

##### Pane resizing #####

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
