##### Load keybindings #####

# source-file ~/.config/tmux/tmux.reset.conf

##### Terminal #####

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

##### General #####

set -g mouse on
set -g history-limit 100000
set -sg escape-time 100
set -g set-clipboard on

##### Windows #####

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# set -g automatic-rename on
# set -g allow-rename off

set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

##### Vi mode #####

setw -g mode-keys vi
set -g status-keys vi

##### Reload #####

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded tmux config"


##### Current directory #####

# Keep default tmux split keys, but preserve current directory

bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"


##### Pane navigation (Neovim style) #####

# Prefix + h/j/k/l

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


##### Pane resizing #####

# Prefix + H/J/K/L

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5


##### Copy mode #####

# v = character selection
bind -T copy-mode-vi v send -X begin-selection

# V = line selection
bind -T copy-mode-vi V send -X select-line

# y = copy
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# cancel
bind -T copy-mode-vi Escape send -X cancel

# Zoom pane
bind z resize-pane -Z

# Toggle synchronized panes
bind * setw synchronize-panes

##### plugins #####
# please make sure to run the following command to install TPM and plugins:
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm 

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

set -g @resurrect-strategy-nvim 'session'

##### Catppuccin #####

set -g status-position top

set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavor "mocha"

set -g @catppuccin_window_status_style "rounded"

set -g @catppuccin_window_left_separator ""

set -g @catppuccin_window_right_separator " "

set -g @catppuccin_window_middle_separator " █"

set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"

set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"

set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}" # 󰊓

set -g @catppuccin_status_modules_right "directory" # date_time"

set -g @catppuccin_status_modules_left "session"

set -g @catppuccin_status_left_separator  " "

set -g @catppuccin_status_right_separator " "

set -g @catppuccin_status_right_separator_inverse "no"

set -g @catppuccin_status_fill "icon"

set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{b:pane_current_path}"

set -g status-left-length 30
# set -g status-left "#{E:@catppuccin_status_session}"

# set -g status-right "#{E:@catppuccin_status_directory}"

##### TPM must be last #####

run '~/.tmux/plugins/tpm/tpm'

# after everything is set up, you can reload the config file by typing <prefix> + r and
# ~/.tmux/plugins/tpm/bin/install_plugins (to install plugins, must be run inside tmux) 
# or ~/.tmux/plugins/tpm/bin/update_plugins all (to update plugins)
# or ctrl + b + I (capital i, to fetch the plugin and source it, inside tmux)
# then tmux kill-server and tmux start-server to restart tmux with the new configuration
